services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: olyxmedia
      POSTGRES_PASSWORD: olyxmedia
      POSTGRES_DB: olyxmedia
    ports:
      - "5432:5432"
    volumes:
      - olyxmedia_db_data:/var/lib/postgresql/data

volumes:
  olyxmedia_db_data:
